
API_VERSION = 3.9
SERVER_NAME= 'https://elsa408.asuscomm.com'

PERSONAL_ACCESS_TOKEN_NAME = 'userTransfer'
PERSONAL_ACCESS_TOKEN_SECRET = 'NAhwmOYRRQq5loKD/4XOdw==:8mt9N8jBsiGzS7LhxTkGFLm1c7Dt1b6E'
DEFAULT_USER_PASSWORD = 'tester123'
